version: "3.8"

services:
  backend: 
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    depends_on:
      - mongodb 
    ports:
      - 5000:5000
    environment:
      USER_NAME: mongo-user 
      USER_PWD: mongo-password 
      MONGO_URI: mongodb://mongo-user:mongo-password@mongodb:27017/mydb
  
  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile 
    depends_on: 
      - backend 
    ports: 
      - 80:80
  
  mongodb:
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: mongo-password
    ports:
      - 27017:27017
    volumes:
      -  mongo-data:/data/db

volumes:
  mongo-data: