apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: backend-deployment
  labels:
    app: backend 
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: backend 
  template:
    metadata: 
      labels:
        app: backend
    spec: 
      containers: 
      - name: backend 
        image: harbeylefty17/k8s-demo-backend
        ports:
        - containerPort: 5000
        env: 
        - name: USER_NAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret 
              key: mongo-user
        - name: USER_PWD 
          valueFrom: 
            secretKeyRef:
              name: mongo-secret 
              key: mongo-password 
        - name: MONGO_URI 
          valueFrom:
            configMapKeyRef:
              name: mongo-config 
              key: MONGO_URI 
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits: 
            memory: "256Mi"
            cpu: "500m"

---
apiVersion: v1 
kind: Service 
metadata: 
  name: backend-service 
spec: 
  type: NodePort 
  selector:
    app: backend 
  ports: 
  - protocol: TCP 
    port: 5000
    targetPort: 5000
    nodePort: 30001